

let CountriesList = [{	code	:	"	AFG	"	,	country	:	"	Afghanistan	"	}	,
{	code	:	"	ALB	"	,	country	:	"	Albania	"	}	,
{	code	:	"	DZA	"	,	country	:	"	Algeria	"	}	,
{	code	:	"	ASM	"	,	country	:	"	American Samoa	"	}	,
{	code	:	"	AND	"	,	country	:	"	Andorra	"	}	,
{	code	:	"	AGO	"	,	country	:	"	Angola	"	}	,
{	code	:	"	AIA	"	,	country	:	"	Anguilla	"	}	,
{	code	:	"	ATA	"	,	country	:	"	Antarctica	"	}	,
{	code	:	"	ATG	"	,	country	:	"	Antigua and Barbuda	"	}	,
{	code	:	"	ARG	"	,	country	:	"	Argentina	"	}	,
{	code	:	"	ARM	"	,	country	:	"	Armenia	"	}	,
{	code	:	"	ABW	"	,	country	:	"	Aruba	"	}	,
{	code	:	"	AUS	"	,	country	:	"	Australia	"	}	,
{	code	:	"	AUT	"	,	country	:	"	Austria	"	}	,
{	code	:	"	AZE	"	,	country	:	"	Azerbaijan	"	}	,
{	code	:	"	BHS	"	,	country	:	"	Bahamas (the)	"	}	,
{	code	:	"	BHR	"	,	country	:	"	Bahrain	"	}	,
{	code	:	"	BGD	"	,	country	:	"	Bangladesh	"	}	,
{	code	:	"	BRB	"	,	country	:	"	Barbados	"	}	,
{	code	:	"	BLR	"	,	country	:	"	Belarus	"	}	,
{	code	:	"	BEL	"	,	country	:	"	Belgium	"	}	,
{	code	:	"	BLZ	"	,	country	:	"	Belize	"	}	,
{	code	:	"	BEN	"	,	country	:	"	Benin	"	}	,
{	code	:	"	BMU	"	,	country	:	"	Bermuda	"	}	,
{	code	:	"	BTN	"	,	country	:	"	Bhutan	"	}	,
{	code	:	"	BOL	"	,	country	:	"	Bolivia (Plurinational State of)	"	}	,
{	code	:	"	BES	"	,	country	:	"	Bonaire, Sint Eustatius and Saba	"	}	,
{	code	:	"	BIH	"	,	country	:	"	Bosnia and Herzegovina	"	}	,
{	code	:	"	BWA	"	,	country	:	"	Botswana	"	}	,
{	code	:	"	BVT	"	,	country	:	"	Bouvet Island	"	}	,
{	code	:	"	BRA	"	,	country	:	"	Brazil	"	}	,
{	code	:	"	IOT	"	,	country	:	"	British Indian Ocean Territory (the)	"	}	,
{	code	:	"	BRN	"	,	country	:	"	Brunei Darussalam	"	}	,
{	code	:	"	BGR	"	,	country	:	"	Bulgaria	"	}	,
{	code	:	"	BFA	"	,	country	:	"	Burkina Faso	"	}	,
{	code	:	"	BDI	"	,	country	:	"	Burundi	"	}	,
{	code	:	"	CPV	"	,	country	:	"	Cabo Verde	"	}	,
{	code	:	"	KHM	"	,	country	:	"	Cambodia	"	}	,
{	code	:	"	CMR	"	,	country	:	"	Cameroon	"	}	,
{	code	:	"	CAN	"	,	country	:	"	Canada	"	}	,
{	code	:	"	CYM	"	,	country	:	"	Cayman Islands (the)	"	}	,
{	code	:	"	CAF	"	,	country	:	"	Central African Republic (the)	"	}	,
{	code	:	"	TCD	"	,	country	:	"	Chad	"	}	,
{	code	:	"	CHL	"	,	country	:	"	Chile	"	}	,
{	code	:	"	CHN	"	,	country	:	"	China	"	}	,
{	code	:	"	CXR	"	,	country	:	"	Christmas Island	"	}	,
{	code	:	"	CCK	"	,	country	:	"	Cocos (Keeling) Islands (the)	"	}	,
{	code	:	"	COL	"	,	country	:	"	Colombia	"	}	,
{	code	:	"	COM	"	,	country	:	"	Comoros (the)	"	}	,
{	code	:	"	COD	"	,	country	:	"	Congo (the Democratic Republic of the)	"	}	,
{	code	:	"	COG	"	,	country	:	"	Congo (the)	"	}	,
{	code	:	"	COK	"	,	country	:	"	Cook Islands (the)	"	}	,
{	code	:	"	CRI	"	,	country	:	"	Costa Rica	"	}	,
{	code	:	"	HRV	"	,	country	:	"	Croatia	"	}	,
{	code	:	"	CUB	"	,	country	:	"	Cuba	"	}	,
{	code	:	"	CUW	"	,	country	:	"	Curaçao	"	}	,
{	code	:	"	CYP	"	,	country	:	"	Cyprus	"	}	,
{	code	:	"	CZE	"	,	country	:	"	Czechia	"	}	,
{	code	:	"	CIV	"	,	country	:	"	Côte d'Ivoire	"	}	,
{	code	:	"	DNK	"	,	country	:	"	Denmark	"	}	,
{	code	:	"	DJI	"	,	country	:	"	Djibouti	"	}	,
{	code	:	"	DMA	"	,	country	:	"	Dominica	"	}	,
{	code	:	"	DOM	"	,	country	:	"	Dominican Republic (the)	"	}	,
{	code	:	"	ECU	"	,	country	:	"	Ecuador	"	}	,
{	code	:	"	EGY	"	,	country	:	"	Egypt	"	}	,
{	code	:	"	SLV	"	,	country	:	"	El Salvador	"	}	,
{	code	:	"	GNQ	"	,	country	:	"	Equatorial Guinea	"	}	,
{	code	:	"	ERI	"	,	country	:	"	Eritrea	"	}	,
{	code	:	"	EST	"	,	country	:	"	Estonia	"	}	,
{	code	:	"	SWZ	"	,	country	:	"	Eswatini	"	}	,
{	code	:	"	ETH	"	,	country	:	"	Ethiopia	"	}	,
{	code	:	"	FLK	"	,	country	:	"	Falkland Islands (the) [Malvinas]	"	}	,
{	code	:	"	FRO	"	,	country	:	"	Faroe Islands (the)	"	}	,
{	code	:	"	FJI	"	,	country	:	"	Fiji	"	}	,
{	code	:	"	FIN	"	,	country	:	"	Finland	"	}	,
{	code	:	"	FRA	"	,	country	:	"	France	"	}	,
{	code	:	"	GUF	"	,	country	:	"	French Guiana	"	}	,
{	code	:	"	PYF	"	,	country	:	"	French Polynesia	"	}	,
{	code	:	"	ATF	"	,	country	:	"	French Southern Territories (the)	"	}	,
{	code	:	"	GAB	"	,	country	:	"	Gabon	"	}	,
{	code	:	"	GMB	"	,	country	:	"	Gambia (the)	"	}	,
{	code	:	"	GEO	"	,	country	:	"	Georgia	"	}	,
{	code	:	"	DEU	"	,	country	:	"	Germany	"	}	,
{	code	:	"	GHA	"	,	country	:	"	Ghana	"	}	,
{	code	:	"	GIB	"	,	country	:	"	Gibraltar	"	}	,
{	code	:	"	GRC	"	,	country	:	"	Greece	"	}	,
{	code	:	"	GRL	"	,	country	:	"	Greenland	"	}	,
{	code	:	"	GRD	"	,	country	:	"	Grenada	"	}	,
{	code	:	"	GLP	"	,	country	:	"	Guadeloupe	"	}	,
{	code	:	"	GUM	"	,	country	:	"	Guam	"	}	,
{	code	:	"	GTM	"	,	country	:	"	Guatemala	"	}	,
{	code	:	"	GGY	"	,	country	:	"	Guernsey	"	}	,
{	code	:	"	GIN	"	,	country	:	"	Guinea	"	}	,
{	code	:	"	GNB	"	,	country	:	"	Guinea-Bissau	"	}	,
{	code	:	"	GUY	"	,	country	:	"	Guyana	"	}	,
{	code	:	"	HTI	"	,	country	:	"	Haiti	"	}	,
{	code	:	"	HMD	"	,	country	:	"	Heard Island and McDonald Islands	"	}	,
{	code	:	"	VAT	"	,	country	:	"	Holy See (the)	"	}	,
{	code	:	"	HND	"	,	country	:	"	Honduras	"	}	,
{	code	:	"	HKG	"	,	country	:	"	Hong Kong	"	}	,
{	code	:	"	HUN	"	,	country	:	"	Hungary	"	}	,
{	code	:	"	ISL	"	,	country	:	"	Iceland	"	}	,
{	code	:	"	IND	"	,	country	:	"	India	"	}	,
{	code	:	"	IDN	"	,	country	:	"	Indonesia	"	}	,
{	code	:	"	IRN	"	,	country	:	"	Iran (Islamic Republic of)	"	}	,
{	code	:	"	IRQ	"	,	country	:	"	Iraq	"	}	,
{	code	:	"	IRL	"	,	country	:	"	Ireland	"	}	,
{	code	:	"	IMN	"	,	country	:	"	Isle of Man	"	}	,
{	code	:	"	ISR	"	,	country	:	"	Israel	"	}	,
{	code	:	"	ITA	"	,	country	:	"	Italy	"	}	,
{	code	:	"	JAM	"	,	country	:	"	Jamaica	"	}	,
{	code	:	"	JPN	"	,	country	:	"	Japan	"	}	,
{	code	:	"	JEY	"	,	country	:	"	Jersey	"	}	,
{	code	:	"	JOR	"	,	country	:	"	Jordan	"	}	,
{	code	:	"	KAZ	"	,	country	:	"	Kazakhstan	"	}	,
{	code	:	"	KEN	"	,	country	:	"	Kenya	"	}	,
{	code	:	"	KIR	"	,	country	:	"	Kiribati	"	}	,
{	code	:	"	PRK	"	,	country	:	"	Korea (the Democratic People's Republic of)	"	}	,
{	code	:	"	KOR	"	,	country	:	"	Korea (the Republic of)	"	}	,
{	code	:	"	KWT	"	,	country	:	"	Kuwait	"	}	,
{	code	:	"	KGZ	"	,	country	:	"	Kyrgyzstan	"	}	,
{	code	:	"	LAO	"	,	country	:	"	Lao People's Democratic Republic (the)	"	}	,
{	code	:	"	LVA	"	,	country	:	"	Latvia	"	}	,
{	code	:	"	LBN	"	,	country	:	"	Lebanon	"	}	,
{	code	:	"	LSO	"	,	country	:	"	Lesotho	"	}	,
{	code	:	"	LBR	"	,	country	:	"	Liberia	"	}	,
{	code	:	"	LBY	"	,	country	:	"	Libya	"	}	,
{	code	:	"	LIE	"	,	country	:	"	Liechtenstein	"	}	,
{	code	:	"	LTU	"	,	country	:	"	Lithuania	"	}	,
{	code	:	"	LUX	"	,	country	:	"	Luxembourg	"	}	,
{	code	:	"	MAC	"	,	country	:	"	Macao	"	}	,
{	code	:	"	MDG	"	,	country	:	"	Madagascar	"	}	,
{	code	:	"	MWI	"	,	country	:	"	Malawi	"	}	,
{	code	:	"	MYS	"	,	country	:	"	Malaysia	"	}	,
{	code	:	"	MDV	"	,	country	:	"	Maldives	"	}	,
{	code	:	"	MLI	"	,	country	:	"	Mali	"	}	,
{	code	:	"	MLT	"	,	country	:	"	Malta	"	}	,
{	code	:	"	MHL	"	,	country	:	"	Marshall Islands (the)	"	}	,
{	code	:	"	MTQ	"	,	country	:	"	Martinique	"	}	,
{	code	:	"	MRT	"	,	country	:	"	Mauritania	"	}	,
{	code	:	"	MUS	"	,	country	:	"	Mauritius	"	}	,
{	code	:	"	MYT	"	,	country	:	"	Mayotte	"	}	,
{	code	:	"	MEX	"	,	country	:	"	Mexico	"	}	,
{	code	:	"	FSM	"	,	country	:	"	Micronesia (Federated States of)	"	}	,
{	code	:	"	MDA	"	,	country	:	"	Moldova (the Republic of)	"	}	,
{	code	:	"	MCO	"	,	country	:	"	Monaco	"	}	,
{	code	:	"	MNG	"	,	country	:	"	Mongolia	"	}	,
{	code	:	"	MNE	"	,	country	:	"	Montenegro	"	}	,
{	code	:	"	MSR	"	,	country	:	"	Montserrat	"	}	,
{	code	:	"	MAR	"	,	country	:	"	Morocco	"	}	,
{	code	:	"	MOZ	"	,	country	:	"	Mozambique	"	}	,
{	code	:	"	MMR	"	,	country	:	"	Myanmar	"	}	,
{	code	:	"	NAM	"	,	country	:	"	Namibia	"	}	,
{	code	:	"	NRU	"	,	country	:	"	Nauru	"	}	,
{	code	:	"	NPL	"	,	country	:	"	Nepal	"	}	,
{	code	:	"	NLD	"	,	country	:	"	Netherlands (the)	"	}	,
{	code	:	"	NCL	"	,	country	:	"	New Caledonia	"	}	,
{	code	:	"	NZL	"	,	country	:	"	New Zealand	"	}	,
{	code	:	"	NIC	"	,	country	:	"	Nicaragua	"	}	,
{	code	:	"	NER	"	,	country	:	"	Niger (the)	"	}	,
{	code	:	"	NGA	"	,	country	:	"	Nigeria	"	}	,
{	code	:	"	NIU	"	,	country	:	"	Niue	"	}	,
{	code	:	"	NFK	"	,	country	:	"	Norfolk Island	"	}	,
{	code	:	"	MNP	"	,	country	:	"	Northern Mariana Islands (the)	"	}	,
{	code	:	"	NOR	"	,	country	:	"	Norway	"	}	,
{	code	:	"	OMN	"	,	country	:	"	Oman	"	}	,
{	code	:	"	PAK	"	,	country	:	"	Pakistan	"	}	,
{	code	:	"	PLW	"	,	country	:	"	Palau	"	}	,
{	code	:	"	PSE	"	,	country	:	"	Palestine, State of	"	}	,
{	code	:	"	PAN	"	,	country	:	"	Panama	"	}	,
{	code	:	"	PNG	"	,	country	:	"	Papua New Guinea	"	}	,
{	code	:	"	PRY	"	,	country	:	"	Paraguay	"	}	,
{	code	:	"	PER	"	,	country	:	"	Peru	"	}	,
{	code	:	"	PHL	"	,	country	:	"	Philippines (the)	"	}	,
{	code	:	"	PCN	"	,	country	:	"	Pitcairn	"	}	,
{	code	:	"	POL	"	,	country	:	"	Poland	"	}	,
{	code	:	"	PRT	"	,	country	:	"	Portugal	"	}	,
{	code	:	"	PRI	"	,	country	:	"	Puerto Rico	"	}	,
{	code	:	"	QAT	"	,	country	:	"	Qatar	"	}	,
{	code	:	"	MKD	"	,	country	:	"	Republic of North Macedonia	"	}	,
{	code	:	"	ROU	"	,	country	:	"	Romania	"	}	,
{	code	:	"	RUS	"	,	country	:	"	Russian Federation (the)	"	}	,
{	code	:	"	RWA	"	,	country	:	"	Rwanda	"	}	,
{	code	:	"	REU	"	,	country	:	"	Réunion	"	}	,
{	code	:	"	BLM	"	,	country	:	"	Saint Barthélemy	"	}	,
{	code	:	"	SHN	"	,	country	:	"	Saint Helena, Ascension and Tristan da Cunha	"	}	,
{	code	:	"	KNA	"	,	country	:	"	Saint Kitts and Nevis	"	}	,
{	code	:	"	LCA	"	,	country	:	"	Saint Lucia	"	}	,
{	code	:	"	MAF	"	,	country	:	"	Saint Martin (French part)	"	}	,
{	code	:	"	SPM	"	,	country	:	"	Saint Pierre and Miquelon	"	}	,
{	code	:	"	VCT	"	,	country	:	"	Saint Vincent and the Grenadines	"	}	,
{	code	:	"	WSM	"	,	country	:	"	Samoa	"	}	,
{	code	:	"	SMR	"	,	country	:	"	San Marino	"	}	,
{	code	:	"	STP	"	,	country	:	"	Sao Tome and Principe	"	}	,
{	code	:	"	SAU	"	,	country	:	"	Saudi Arabia	"	}	,
{	code	:	"	SEN	"	,	country	:	"	Senegal	"	}	,
{	code	:	"	SRB	"	,	country	:	"	Serbia	"	}	,
{	code	:	"	SYC	"	,	country	:	"	Seychelles	"	}	,
{	code	:	"	SLE	"	,	country	:	"	Sierra Leone	"	}	,
{	code	:	"	SGP	"	,	country	:	"	Singapore	"	}	,
{	code	:	"	SXM	"	,	country	:	"	Sint Maarten (Dutch part)	"	}	,
{	code	:	"	SVK	"	,	country	:	"	Slovakia	"	}	,
{	code	:	"	SVN	"	,	country	:	"	Slovenia	"	}	,
{	code	:	"	SLB	"	,	country	:	"	Solomon Islands	"	}	,
{	code	:	"	SOM	"	,	country	:	"	Somalia	"	}	,
{	code	:	"	ZAF	"	,	country	:	"	South Africa	"	}	,
{	code	:	"	SGS	"	,	country	:	"	South Georgia and the South Sandwich Islands	"	}	,
{	code	:	"	SSD	"	,	country	:	"	South Sudan	"	}	,
{	code	:	"	ESP	"	,	country	:	"	Spain	"	}	,
{	code	:	"	LKA	"	,	country	:	"	Sri Lanka	"	}	,
{	code	:	"	SDN	"	,	country	:	"	Sudan (the)	"	}	,
{	code	:	"	SUR	"	,	country	:	"	Suriname	"	}	,
{	code	:	"	SJM	"	,	country	:	"	Svalbard and Jan Mayen	"	}	,
{	code	:	"	SWE	"	,	country	:	"	Sweden	"	}	,
{	code	:	"	CHE	"	,	country	:	"	Switzerland	"	}	,
{	code	:	"	SYR	"	,	country	:	"	Syrian Arab Republic	"	}	,
{	code	:	"	TWN	"	,	country	:	"	Taiwan (Province of China)	"	}	,
{	code	:	"	TJK	"	,	country	:	"	Tajikistan	"	}	,
{	code	:	"	TZA	"	,	country	:	"	Tanzania, United Republic of	"	}	,
{	code	:	"	THA	"	,	country	:	"	Thailand	"	}	,
{	code	:	"	TLS	"	,	country	:	"	Timor-Leste	"	}	,
{	code	:	"	TGO	"	,	country	:	"	Togo	"	}	,
{	code	:	"	TKL	"	,	country	:	"	Tokelau	"	}	,
{	code	:	"	TON	"	,	country	:	"	Tonga	"	}	,
{	code	:	"	TTO	"	,	country	:	"	Trinidad and Tobago	"	}	,
{	code	:	"	TUN	"	,	country	:	"	Tunisia	"	}	,
{	code	:	"	TUR	"	,	country	:	"	Turkey	"	}	,
{	code	:	"	TKM	"	,	country	:	"	Turkmenistan	"	}	,
{	code	:	"	TCA	"	,	country	:	"	Turks and Caicos Islands (the)	"	}	,
{	code	:	"	TUV	"	,	country	:	"	Tuvalu	"	}	,
{	code	:	"	UGA	"	,	country	:	"	Uganda	"	}	,
{	code	:	"	UKR	"	,	country	:	"	Ukraine	"	}	,
{	code	:	"	ARE	"	,	country	:	"	United Arab Emirates (the)	"	}	,
{	code	:	"	GBR	"	,	country	:	"	United Kingdom of Great Britain and Northern Ireland (the)	"	}	,
{	code	:	"	GBR	"	,	country	:	"	England	"	}	,
{	code	:	"	UMI	"	,	country	:	"	United States Minor Outlying Islands (the)	"	}	,
{	code	:	"	USA	"	,	country	:	"	United States of America (the)	"	}	,
{	code	:	"	URY	"	,	country	:	"	Uruguay	"	}	,
{	code	:	"	UZB	"	,	country	:	"	Uzbekistan	"	}	,
{	code	:	"	VUT	"	,	country	:	"	Vanuatu	"	}	,
{	code	:	"	VEN	"	,	country	:	"	Venezuela (Bolivarian Republic of)	"	}	,
{	code	:	"	VNM	"	,	country	:	"	Viet Nam	"	}	,
{	code	:	"	VGB	"	,	country	:	"	Virgin Islands (British)	"	}	,
{	code	:	"	VIR	"	,	country	:	"	Virgin Islands (U.S.)	"	}	,
{	code	:	"	WLF	"	,	country	:	"	Wallis and Futuna	"	}	,
{	code	:	"	ESH	"	,	country	:	"	Western Sahara	"	}	,
{	code	:	"	YEM	"	,	country	:	"	Yemen	"	}	,
{	code	:	"	ZMB	"	,	country	:	"	Zambia	"	}	,
{	code	:	"	ZWE	"	,	country	:	"	Zimbabwe	"	}	,
{	code	:	"	ALA	"	,	country	:	"	Åland Islands	"	}]

export default CountriesList;